import = ["/Users/long2ice/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[shell]
args = ["-l", "-c", "zellij attach --index 0 --create"]
program = "/usr/local/bin/fish"

[window]
dynamic_padding = true
opacity = 0.95
startup_mode = "Maximized"

[window.position]
x = 0
y = 0

[keyboard]
bindings = [{ key = "NumpadEnter", chars = "\n" }]
